"""HWP -> HTML 변환 스크립트

사용법:
  python hwp2html.py <input.hwp> <output.html>

요구사항(로컬/서버에 설치 필요):
  - python 3
  - hwp5html 명령 (pyhwp 패키지에 포함). 예:
      pip install pyhwp

동작:
  1) hwp5html로 input을 outdir로 변환
  2) 생성된 html/xhtml 본문을 읽어 output.html에 UTF-8로 저장

주의:
  - 변환 결과의 품질은 hwp5html 지원 수준에 의존합니다.
  - 이 스크립트는 "파이프라인"만 제공하며, 운영 환경에서 사용 시 별도 검증이 필요합니다.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def _read_text(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def _find_main_html(outdir: Path) -> Path | None:
    # hwp5html은 outdir 아래에 index.html 또는 index.xhtml 등을 생성
    candidates = [
        outdir / "index.html",
        outdir / "index.xhtml",
        outdir / "index.htm",
    ]
    for c in candidates:
        if c.exists():
            return c
    # fallback: 아무 html/xhtml 파일 1개
    for c in outdir.rglob("*.xhtml"):
        return c
    for c in outdir.rglob("*.html"):
        return c
    return None


def _extract_body(html: str) -> str:
    # 간단한 body 추출 (정교한 파서가 없을 때를 위한 최소 구현)
    m = re.search(r"<body[^>]*>([\s\S]*?)</body>", html, flags=re.IGNORECASE)
    return m.group(1).strip() if m else html


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("Usage: python hwp2html.py <input.hwp> <output.html>", file=sys.stderr)
        return 2

    in_path = Path(argv[1]).resolve()
    out_path = Path(argv[2]).resolve()

    if not in_path.exists():
        print(f"Input not found: {in_path}", file=sys.stderr)
        return 3

    # outdir
    outdir = Path(tempfile.mkdtemp(prefix="kma-hwp5html-"))
    try:
        # hwp5html 실행
        # 예: hwp5html --output <outdir> <input>
        cmd = ["hwp5html", "--output", str(outdir), str(in_path)]
        r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, encoding="utf-8", errors="replace")
        if r.returncode != 0:
            print("hwp5html failed", file=sys.stderr)
            print(r.stderr or r.stdout, file=sys.stderr)
            return 10

        main_html = _find_main_html(outdir)
        if not main_html:
            print("No html generated by hwp5html", file=sys.stderr)
            return 11

        html = _read_text(main_html)
        body = _extract_body(html)

        # css가 있으면 인라인 스타일로 포함
        css_text = ""
        css_file = outdir / "styles.css"
        if css_file.exists():
            css_text = _read_text(css_file)

        final = "<div class=\"kma-hwp\">\n"
        if css_text:
            final += f"<style>\n{css_text}\n</style>\n"
        final += body
        final += "\n</div>\n"

        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(final, encoding="utf-8")
        return 0
    finally:
        shutil.rmtree(outdir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
